---
- include: "{{vtq}}/vtq.yml"
  vars:
    pathogen_plugin_urls:
      - https://github.com/Valloric/YouCompleteMe
- hosts: all
  tasks:
      - name: Ensure CMake is installed.
        apt: pkg=cmake state=present

      - name: Compile YCM.
        shell: ./install.sh chdir=~/.vim/bundle/YouCompleteMe/
